"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv


load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = Path(os.getenv("DATA_DIR", BASE_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str | None = os.getenv(key="SECRET_KEY")

PROD: bool = os.getenv("IS_PROD", "False") == "True"

DEBUG : bool = not PROD

SITE_DOMAIN: str = os.getenv("SITE_DOMAIN", "")

LOCAL_ALLOW: list[str] = ["localhost", "127.0.0.1"]
PROD_ALLOW: list[str] = [SITE_DOMAIN]

if PROD:
    ALLOWED_HOSTS: list[str] = PROD_ALLOW
else:
    ALLOWED_HOSTS: list[str] = LOCAL_ALLOW

CSRF_TRUSTED_ORIGINS: list[str] = [f"https://{SITE_DOMAIN}"] if PROD else []

CSRF_COOKIE_SECURE: bool = PROD
SESSION_COOKIE_SECURE: bool = PROD
SECURE_SSL_REDIRECT: bool = PROD

SECURE_PROXY_SSL_HEADER: tuple[str, str] = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS: int = 30
SECURE_HSTS_INCLUDE_SUBDOMAINS: bool = PROD
SECURE_HSTS_PRELOAD: bool = PROD

# Cloudflare Turnstile, on the public prayer form only. Both blank, which is the
# default, switches the widget and the verification off entirely. That off switch
# is what lets the test suite and a fresh clone run with no keys and no network.
# lucid.checks guards against them being blank or still on a test key in prod.
TURNSTILE_SITE_KEY: str = os.getenv("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY: str = os.getenv("TURNSTILE_SECRET_KEY", "")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Only for naturaltime ("2 hours ago") on the staff page.
    "django.contrib.humanize",
    "lucid",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves static files from gunicorn, since Caddy only reverse-proxies.
    # Must sit directly below SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Holds admin/base_site.html. DIRS is searched before APP_DIRS, which is
        # the only reason that override wins over the copy shipped inside
        # django.contrib.admin. App templates still live in lucid/templates/.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "db.sqlite3",
        "OPTIONS": {
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
            "transaction_mode": "IMMEDIATE",
            "timeout": 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` writes to. Not used in dev (DEBUG=True serves straight
# from each app's static/ dir), required in prod.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Hashes filenames for cache-busting and pre-compresses them.
        # Requires `collectstatic` to have run before the app boots in prod.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
